✨ Metrics info card
interest-protocol/sui-coins pull request #100
Opened 2024-02-08 22:52 UTC by MarioBatalha

2024-02-09 08:57 UTC, git-marcopitra requested changes

2024-02-09 08:57 UTC, git-marcopitra commented on components/svg/pool.tsx
> +      fill="#1B1B1F"
currentColor

2024-02-09 08:57 UTC, git-marcopitra commented on components/svg/chart.tsx
> +      fill="#1B1B1F"
currentColor

2024-02-09 08:57 UTC, git-marcopitra commented on components/svg/usd.tsx
> +  return (
remove the `return`

2024-02-09 08:57 UTC, git-marcopitra commented on components/svg/usd.tsx
> +        fill="#1B1B1F"
`currentColor`

2024-02-09 08:57 UTC, git-marcopitra commented on views/metrics/index.tsx
>  const Metrics: FC = () => (
add an empty line after the imports

2024-02-09 08:57 UTC, git-marcopitra commented on views/metrics/info-card/index.tsx
> +  const [data, setData] = useState<any[] | null>(null);
do not use `any`, go to `sui-interface` to see how are we handling it

2024-02-09 08:57 UTC, git-marcopitra commented on views/metrics/info-card/index.tsx
> +      gridColumn="1/-1"
I don't know why we have this line, I think that we don't have a grid as parent, if we have it's ok

2024-02-09 13:56 UTC, git-marcopitra commented
It's not responsive

2024-02-12 17:07 UTC, git-marcopitra requested changes

2024-02-12 17:07 UTC, git-marcopitra commented on views/metrics/info-card/index.tsx
> +      gridColumn="1/-1"
remove this line

2024-02-12 20:10 UTC, git-marcopitra commented
<img width="760" alt="image" src="https://github.com/interest-protocol/sui-coins/assets/59171412/a0e16880-7126-4f38-a806-b061d9c17e84">

2024-02-12 23:49 UTC, git-marcopitra requested changes

2024-02-12 23:49 UTC, git-marcopitra commented on views/metrics/index.tsx
> +    <Box
revert these changes

2024-02-13 00:29 UTC, KipandaJr requested changes
![image](https://github.com/interest-protocol/sui-coins/assets/34079870/e552dde2-b95b-4185-80d3-70b8f9dd88ad)

Revert that change that Marco suggest to u... put a `variant="container"` on that `Box`

2024-02-13 20:22 UTC, closed without merging