:recycle: refactor select token icon
interest-protocol/sui-coins pull request #118
Opened 2024-02-13 19:01 UTC by MarioBatalha

2024-02-13 19:07 UTC, git-marcopitra commented
![image](https://github.com/interest-protocol/sui-coins/assets/59171412/7ffbeb8a-8d17-422b-9391-565e4835c890)
It's supposed to have the same size

2024-02-13 19:08 UTC, git-marcopitra commented
And there is a bug when I select **FUD** the pug

2024-02-14 22:58 UTC, KipandaJr requested changes
Token selected  ![image](https://github.com/interest-protocol/sui-coins/assets/34079870/c3155ac3-7850-4ed8-8af6-aec6a8361feb)
Token on Input 
![image](https://github.com/interest-protocol/sui-coins/assets/34079870/783aab39-e7a7-4540-85dc-fc1b9ff8eb3f)


Its is expected?

2024-02-14 23:15 UTC, MarioBatalha commented
> Token selected ![image](https://private-user-images.githubusercontent.com/34079870/304899445-c3155ac3-7850-4ed8-8af6-aec6a8361feb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NTI1OTEsIm5iZiI6MTcwNzk1MjI5MSwicGF0aCI6Ii8zNDA3OTg3MC8zMDQ4OTk0NDUtYzMxNTVhYzMtNzg1MC00ZWQ4LThhZjYtYWVjNmE4MzYxZmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDIzMTEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2Y2I0YmYxYTYxN2ZhZjNmNzk0ZGEzYTQyZjlmMDdkNGYyMzIyMmNiNDIzMzAzNjRlMDc0ZTY4MjZlMzJkMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WcxFrgCqsudbg_jWPuu-w51Y26dU8hH0ML3EoknWUs0) Token on Input ![image](https://private-user-images.githubusercontent.com/34079870/304899566-783aab39-e7a7-4540-85dc-fc1b9ff8eb3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NTI1OTEsIm5iZiI6MTcwNzk1MjI5MSwicGF0aCI6Ii8zNDA3OTg3MC8zMDQ4OTk1NjYtNzgzYWFiMzktZTdhNy00NTQwLTg1ZGMtZmMxYjlmZjhlYjNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDIzMTEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNzQyMjRiZDJiZDllOTljZDNhYWUyODYyY2I4MDkwYjFjZDQ3YWJkYzFiY2IwN2UwOGExZWZlMTIwMTA0YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HyH-schUoeV88b8P8gQuwy8lDKms_jIazLUbTTs-7eY)
> 
> Its is expected?

I didn't format the value, it's comes this way from the api.

2024-02-15 20:34 UTC, git-marcopitra requested changes

2024-02-15 20:34 UTC, git-marcopitra commented on constants/index.ts
> +export type CHAIN = 'ETH' | 'BSC' | 'SOL' | 'AVA';
move to `@/interface` and transform type to PascalCase

2024-02-16 00:43 UTC, KipandaJr approved these changes

2024-02-16 20:08 UTC, git-marcopitra approved these changes

2024-02-16 20:20 UTC, atilasousa approved these changes

2024-02-16 20:22 UTC, git-marcopitra approved these changes

2024-02-16 20:22 UTC, merged