:sparkles: New pages and header
interest-protocol/sui-coins pull request #23
Opened 2023-11-21 21:25 UTC by KipandaJr

2023-11-22 06:42 UTC, git-marcopitra approved these changes

2023-11-22 06:44 UTC, git-marcopitra commented
The clicks on nav item are not working correctly on Desktop

2023-11-23 23:45 UTC, MarioBatalha approved these changes

2023-11-23 23:48 UTC, okusindja requested changes

2023-11-23 23:48 UTC, okusindja commented on components/layout/header/index.tsx
> +      mb="0 !important"
please, delete this `mb="0 !important"`, it doesn't work and do not affect on the frontend

2023-11-23 23:48 UTC, okusindja commented on views/pools/index.tsx
> +      <Box
Remove the Box and add Typography

2023-11-23 23:48 UTC, okusindja commented on views/swap/index.tsx
> +      <Box
Remove the Box and add Typography

2023-11-23 23:48 UTC, okusindja commented on views/error/index.tsx
>            fontFamily="Share Tech Mono"
Do we have this fontFamily in our variants? If yes, you shouldn't add the property here.

2023-11-23 23:48 UTC, okusindja commented on views/create-token/hero/title.tsx
>          fontFamily="Proto"
Remove the fontFamily, fontWeight and lineHeight props

2023-11-23 23:48 UTC, okusindja commented on views/create-token/create-token-form/fixed-supply-toggle.tsx
>          <Box>Fixed Supply</Box>
Add Typography here, instead of Box

2023-11-23 23:48 UTC, okusindja commented on utils/toast/index.tsx
>            fontWeight="700"
Remove the fontFamily, fontWeight and lineHeight props

2023-11-23 23:48 UTC, okusindja commented on components/layout/header/nav-bar.tsx
> +        <Box
Fix this. add a Typography as a child in this Box to pass texts inside

2023-11-28 10:12 UTC, merged