:bookmark: feat: release new version
interest-protocol/sui-coins pull request #305
Opened 2024-06-11 02:22 UTC by git-marcopitra

2024-06-11 14:24 UTC, MarioBatalha approved these changes

2024-06-11 21:25 UTC, KipandaJr commented on views/components/select-token-modal/index.tsx
> +      width="25rem"
change this to `max-width=25rem` because this way, the modal break on mobile ui

2024-06-11 21:27 UTC, KipandaJr requested changes

2024-06-11 21:27 UTC, KipandaJr commented on views/components/select-token-modal/index.tsx
> +      width="25rem"
change this to `max-width=25rem` because this way, the modal break on mobile ui

2024-06-12 08:08 UTC, KipandaJr approved these changes

2024-06-17 15:29 UTC, merged