✨ add pool title bar
interest-protocol/sui-coins pull request #31
Opened 2023-11-30 18:43 UTC by okusindja

2023-11-30 23:29 UTC, MarioBatalha approved these changes

2023-12-04 21:10 UTC, KipandaJr requested changes
Check on mobile ui, are weird.

2023-12-04 21:10 UTC, KipandaJr commented on views/pools/index.tsx
>        </Typography>
Remove this title

2023-12-04 21:10 UTC, KipandaJr commented on views/pools/pool-title-bar/index.tsx
> +        </Box>
This box should be ride on mobile

2023-12-04 21:10 UTC, KipandaJr commented on views/pools/pool-title-bar/pool-title-bar.types.ts
> +  poolExitCoin: ReactNode;
why this name like `poolEnterCoin` or `poolExitCoin`?

2023-12-04 21:10 UTC, KipandaJr commented on views/pools/pool-title-bar/pool-title-bar.types.ts
> +export interface PoolTitleBarProps {
miss the function to call on Back button

2023-12-06 19:49 UTC, merged