:sparkles: Adding Pool form
interest-protocol/sui-coins pull request #35
Opened 2023-12-07 15:03 UTC by KipandaJr

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206042570035502

2023-12-07 20:57 UTC, MarioBatalha requested changes

2023-12-07 20:57 UTC, MarioBatalha commented on components/svg/sui-black.tsx
> +    fill="none"
You need to add currentColor

2023-12-08 20:22 UTC, MarioBatalha approved these changes

2023-12-08 20:24 UTC, git-marcopitra requested changes

2023-12-08 20:24 UTC, git-marcopitra commented on components/svg/sui-black.tsx
Remove this icon

2023-12-10 18:13 UTC, git-marcopitra requested changes

2023-12-10 18:13 UTC, git-marcopitra commented on views/components/select-token-modal/index.tsx
> +      <Box mx="0.5rem" mt="0.65rem">
why these weird values?

2023-12-10 18:13 UTC, git-marcopitra commented on views/components/select-token-modal/index.tsx
> +            mb: '1.5rem',
Here as well

2023-12-10 18:13 UTC, git-marcopitra commented on views/pools/pool-form/component/receive-section/line.tsx
> +  return (
Try to avoid `) => { return (` to direct return `) => (`

2023-12-10 18:13 UTC, git-marcopitra commented on views/pools/pool-form/withdraw.tsx
> +  return (
Here as well

2023-12-11 21:43 UTC, atilasousa approved these changes

2023-12-11 22:57 UTC, git-marcopitra approved these changes

2023-12-11 22:57 UTC, merged