Feat new footer
interest-protocol/sui-coins pull request #373
Opened 2024-08-15 21:00 UTC by MarioBatalha

2024-08-15 21:42 UTC, KipandaJr commented on components/layout/footer/index.tsx
> +          &copy; Interest PROTOCOL UI {fullYear}
Capitalize this text

2024-08-15 21:44 UTC, KipandaJr requested changes

2024-08-15 21:44 UTC, KipandaJr commented on components/layout/footer/index.tsx
> +        </Typography>
Capitalize this text

2024-08-15 22:47 UTC, KipandaJr approved these changes

2024-08-16 19:13 UTC, atilasousa approved these changes

2024-08-16 19:18 UTC, merged