♻️ Refactor strict token logic
interest-protocol/sui-coins pull request #509
Opened 2024-11-19 01:03 UTC by MarioBatalha

2024-11-20 18:27 UTC, atilasousa approved these changes

2024-11-20 18:53 UTC, KipandaJr approved these changes

2024-11-24 21:52 UTC, KipandaJr requested changes

2024-11-24 21:52 UTC, KipandaJr commented on views/components/select-token-modal/select-token-modal-body.tsx
> +        data.strictTokensType.includes(search)))
Duplicated condition

2024-11-24 21:52 UTC, KipandaJr commented on views/components/select-token-modal/select-token-modal-body.tsx
> +    )
duplicated condition

2024-11-24 21:52 UTC, KipandaJr commented on utils/coin/index.ts
> +        WORMHOLE_TOKENS[network].find(
why u remove STRICT_TOKEN and added WORMHOLE_TOKENS?

2024-11-24 21:55 UTC, KipandaJr requested changes
![image](https://github.com/user-attachments/assets/1d39431c-0207-4713-b104-2450d6768788)

2024-11-24 22:05 UTC, closed without merging