:recycle: Refactor strict coins from const to endpoint
interest-protocol/sui-coins pull request #513
Opened 2024-11-24 21:31 UTC by git-marcopitra

2024-11-24 21:31 UTC, git-marcopitra commented
Task linked: [CU-8696haf8v ♻️ Refactor STRICT_TOKENS logic](https://app.clickup.com/t/8696haf8v)

2024-11-24 22:01 UTC, MarioBatalha requested changes

2024-11-24 23:27 UTC, git-marcopitra commented on views/swap/swap-init-manager.tsx
> +    const TokenUSDC = tokens?.strictTokens.find(
fix it

2024-11-25 18:27 UTC, KipandaJr approved these changes

2024-11-25 18:28 UTC, MarioBatalha approved these changes

2024-11-25 18:31 UTC, KipandaJr requested changes
![image](https://github.com/user-attachments/assets/033e1d44-98f1-480f-9203-fdc5dc758b3f)
on incinerator in first render they dosent show all tokens

2024-11-25 19:18 UTC, KipandaJr approved these changes

2024-11-25 19:19 UTC, atilasousa approved these changes

2024-11-25 19:30 UTC, merged