:recycle: setting 12 character for symbol in create token
interest-protocol/sui-coins pull request #518
Opened 2024-11-26 12:35 UTC by atilasousa

2024-11-26 18:57 UTC, KipandaJr approved these changes

2024-11-26 19:10 UTC, MarioBatalha approved these changes

2024-11-26 19:15 UTC, MarioBatalha approved these changes

2024-12-02 18:42 UTC, KipandaJr requested changes
![image](https://github.com/user-attachments/assets/681eb22e-7e71-4b08-abc2-8d9268bd52ee)
on Send Page

![image](https://github.com/user-attachments/assets/d9fc5e7f-dc48-4840-8c9e-d14d649a9890)


![image](https://github.com/user-attachments/assets/6385a572-9cbe-4f5f-ba66-1bf195540a19)

2024-12-03 18:12 UTC, KipandaJr approved these changes

2024-12-04 16:10 UTC, MarioBatalha approved these changes

2024-12-09 17:34 UTC, MarioBatalha approved these changes

2024-12-11 08:38 UTC, git-marcopitra approved these changes

2024-12-11 08:38 UTC, merged