:bug: tooltip oveflow
interest-protocol/sui-coins pull request #523
Opened 2024-11-28 07:29 UTC by atilasousa

2024-11-28 14:43 UTC, KipandaJr approved these changes

2024-11-28 17:49 UTC, MarioBatalha requested changes
<img width="1055" alt="Screenshot 2024-11-28 at 17 44 31" src="https://github.com/user-attachments/assets/58667211-b2df-40d3-a803-587eb73b36f1">
<img width="496" alt="Screenshot 2024-11-28 at 17 44 06" src="https://github.com/user-attachments/assets/90fc2769-8ca7-44ac-a7b5-a9ce8e54e500">

Check this breakpoints

2024-11-28 17:51 UTC, MarioBatalha approved these changes

2024-12-11 08:41 UTC, git-marcopitra approved these changes

2024-12-11 08:41 UTC, merged