:sparkles: feat: add airdrop validation message
interest-protocol/sui-coins pull request #529
Opened 2024-12-06 00:40 UTC by MarioBatalha

2024-12-06 00:40 UTC, git-marcopitra commented
Task linked: [CU-8696xjqpr Airdrop info message](https://app.clickup.com/t/8696xjqpr)

2024-12-07 17:53 UTC, KipandaJr reviewed
![image](https://github.com/user-attachments/assets/b07a5f2b-a727-453a-97a7-9819b5d87963)

2024-12-10 18:44 UTC, KipandaJr requested changes
![image](https://github.com/user-attachments/assets/0f8c2250-8a22-4123-9c1f-4954658dfa5f)
its only work for SUI try check with other coins and u will see the bug

2024-12-13 10:52 UTC, KipandaJr approved these changes

2024-12-23 16:09 UTC, closed without merging