🐛  fixing dca balance overflow
interest-protocol/sui-coins pull request #535
Opened 2024-12-15 19:03 UTC by atilasousa

2024-12-15 19:06 UTC, MarioBatalha approved these changes

2024-12-15 19:07 UTC, MarioBatalha approved these changes

2024-12-15 19:09 UTC, KipandaJr approved these changes

2024-12-15 21:29 UTC, git-marcopitra requested changes

2024-12-15 21:29 UTC, git-marcopitra commented on views/swap/input/balance.tsx
> +        maxWidth="12ch"
This is only for the symbol not for the amount

2024-12-15 21:29 UTC, git-marcopitra commented on views/merge/merge-field.tsx
> +            maxWidth="12ch"
This is only for the symbol, not for the amount

2024-12-15 21:29 UTC, git-marcopitra commented on views/dca/input/balance.tsx
> +          variant="body"
This is only for the symbol not for the amount

2024-12-17 20:08 UTC, git-marcopitra approved these changes

2024-12-17 20:09 UTC, merged