:construction: feat: new header implemented
interest-protocol/sui-coins pull request #57
Opened 2024-01-03 06:22 UTC by KipandaJr

2024-01-03 20:08 UTC, git-marcopitra requested changes

2024-01-03 21:50 UTC, MarioBatalha requested changes

2024-01-03 21:50 UTC, MarioBatalha commented on components/wallet/menu-mobile/index.tsx
> +        p="0.25rem"
Put the value from the theme

2024-01-04 20:29 UTC, git-marcopitra requested changes
u r not going over each review

2024-01-04 20:29 UTC, git-marcopitra commented on components/wallet/index.tsx
> +        <Box display={'flex'}>
remove `{}`

2024-01-04 20:29 UTC, git-marcopitra commented on components/wallet/menu-mobile/main-menu.tsx
> +      <Typography m="xl" variant="title" size="small" color="onSurfaceVariant">
this color doesn't exist

2024-01-04 20:29 UTC, git-marcopitra commented on views/pool-details/pool-form/component/receive-section/index.tsx
> +      <Box borderRadius="xs" bg="surface" py="0.5rem">
py value can come from theme

2024-01-04 20:29 UTC, git-marcopitra commented on views/pool-details/pool-form/component/receive-section/index.tsx
>        <Typography variant="body" size="large" mb="1rem">
mb value can come from theme

2024-01-05 20:04 UTC, MarioBatalha approved these changes

2024-01-08 20:17 UTC, git-marcopitra requested changes

2024-01-08 20:17 UTC, git-marcopitra commented on components/wallet/menu-mobile/main-menu.tsx
> +    m="0 1.25rem"
replace `m` to `mx`, and replace the value for theme based

2024-01-08 20:17 UTC, git-marcopitra commented on components/wallet/menu-mobile/main-menu.tsx
> +    justifyItems="unset"
remove this prop

2024-01-08 20:17 UTC, git-marcopitra commented on components/wallet/menu-settings/header.tsx
> +          width="0.469rem"
replace `width` and `height` values to `100%`

2024-01-08 21:49 UTC, merged