:recycle: refactor: swap field
interest-protocol/sui-coins pull request #58
Opened 2024-01-04 23:41 UTC by MarioBatalha

2024-01-04 23:43 UTC, git-marcopitra commented on views/swap/input/header-info.tsx
> +  return (
It's better to be without this `return`

2024-01-04 23:43 UTC, git-marcopitra commented on views/swap/index.tsx
>          borderRadius="2rem"
why not using the theme keys?

2024-01-04 23:50 UTC, KipandaJr requested changes

2024-01-04 23:50 UTC, KipandaJr commented on views/swap/index.tsx
> +            borderColor="#F8F9FD"
check if this color dosent has on theme

2024-01-04 23:50 UTC, KipandaJr commented on views/swap/input/index.tsx
>            lineHeight="1.75rem"
check if theme dosent has this values

2024-01-04 23:50 UTC, KipandaJr commented on views/swap/input/select-token.tsx
> +        py="m"
in this use u can use a `p="m"` instead this approach

2024-01-04 23:50 UTC, KipandaJr commented on views/swap/input/select-token.tsx
>          fontSize="0.875rem"
check this fontSize on theme

2024-01-04 23:51 UTC, git-marcopitra approved these changes

2024-01-04 23:51 UTC, git-marcopitra commented on views/swap/input/select-token.tsx
>          fontSize="0.875rem"
use theme keys

2024-01-04 23:51 UTC, git-marcopitra commented on views/swap/index.tsx
> +            borderColor="#F8F9FD"
color from theme please

2024-01-04 23:51 UTC, git-marcopitra commented on views/swap/input/index.tsx
> +        <Box
remove all the code from here, submit button must to be on the high level

2024-01-04 23:52 UTC, git-marcopitra requested changes
Requesting changes

2024-01-05 01:05 UTC, git-marcopitra requested changes

2024-01-05 01:05 UTC, git-marcopitra commented on views/swap/input/index.tsx
> +            Preview swap
Remove preview button from here

2024-01-05 01:05 UTC, git-marcopitra commented on views/swap/input/select-token.tsx
> +          <Typography size="large" variant="label">
Why it is `PrefixIcon` and not `children`?

2024-01-10 20:41 UTC, git-marcopitra commented on views/swap/input/index.tsx
> +      <Box height="2rem">
I don't recommend to use height by default

2024-01-10 20:47 UTC, git-marcopitra requested changes

2024-01-10 20:47 UTC, git-marcopitra commented on views/swap/input/index.tsx
> +              onChange={() => console.log('range')}
make `onChange` works like [Sui Dapp](https://github.com/interest-protocol/sui-interface)

2024-01-10 20:47 UTC, git-marcopitra commented on views/swap/input/select-token.tsx
> +          Select token
Dynamic value based on Sui Dapp

2024-01-20 09:25 UTC, git-marcopitra approved these changes

2024-01-25 23:45 UTC, git-marcopitra commented
Fix conflits

2024-01-26 20:27 UTC, KipandaJr requested changes
![image](https://github.com/interest-protocol/sui-coins/assets/34079870/b8101b2a-d9f7-4872-8cbc-bf2c3c59a5a2)

2024-01-26 20:27 UTC, KipandaJr commented on components/account-info/avatar.tsx
> +        <Box fontFamily="Proto !important">
why !important

2024-01-26 20:27 UTC, KipandaJr commented on components/account-info/index.tsx
> +            borderColor={isOpen ? '#0053DB33' : 'transparent'}
use the primary color `#0053DB` from theme and add the opacity

2024-01-26 20:27 UTC, KipandaJr commented on components/account-info/index.tsx
> +        borderColor="rgba(0, 83, 219, 0.16)"
check this color

2024-01-26 20:27 UTC, KipandaJr commented on components/account-info/index.tsx
> +        p="0.25rem"
get on theme

2024-01-26 20:27 UTC, KipandaJr commented on components/account-info/mobile-menu-options.tsx
> +      gap="1rem"
get on theme

2024-01-26 20:27 UTC, KipandaJr commented on views/components/pool-title-bar/index.tsx
> +    px="1.5rem"
get on the theme

2024-01-26 20:27 UTC, KipandaJr commented on views/components/pool-title-bar/index.tsx
> +      fontSize={['1.5rem', '1.5rem', '2rem', '2rem']}
get on the theme

2024-01-26 20:27 UTC, KipandaJr commented on views/components/select-token-modal/token-modal-item.tsx
> +      bg={selected ? 'rgba(0, 83, 219, 0.08)' : 'unset'}
get this color on theme

2024-02-07 20:12 UTC, merged