:sparkles: Adding Top Pool and Coins tables
interest-protocol/sui-coins pull request #72
Opened 2024-01-16 21:59 UTC by KipandaJr

2024-01-17 20:08 UTC, MarioBatalha requested changes

2024-01-17 20:08 UTC, MarioBatalha commented on views/metrics/top-tables/table.types.ts
> +  title?: string;
Must be required not optional

2024-01-17 20:08 UTC, MarioBatalha commented on views/metrics/top-tables/top-coins-table/top-pools-table-head.tsx
> +          Coin
This data could be dynamic

2024-01-17 20:08 UTC, MarioBatalha commented on views/metrics/top-tables/top-pools-table/top-pools-table-head.tsx
> +          Token Pair
This data also could be dynamic

2024-01-25 19:50 UTC, git-marcopitra commented
@KipandaJr logic to fill the real values is on `sui-interface`, take a look

2024-01-25 19:53 UTC, git-marcopitra requested changes

2024-01-25 19:53 UTC, git-marcopitra commented on views/metrics/top-tables/table-head.tsx
> +  return (
remove return

2024-01-25 19:53 UTC, git-marcopitra commented on views/metrics/top-tables/table-row.tsx
> +      px="2.25rem"
If there is no this value on the theme use the near one

2024-01-25 19:53 UTC, git-marcopitra commented on views/metrics/top-tables/top-coins-table/index.tsx
> +  return (
remove the return

2024-01-25 19:53 UTC, git-marcopitra commented on views/metrics/top-tables/top-coins-table/top-pools-table-body.tsx
> +  return !loading ? (
convert it to `if (loading) return`

2024-01-25 19:53 UTC, git-marcopitra commented on views/metrics/top-tables/top-pools-table/index.tsx
> +  return (
Remove return

2024-01-25 19:53 UTC, git-marcopitra commented on views/metrics/top-tables/top-pools-table/top-pools-table-body.tsx
> +  return !loading ? (
Convert it to `if (loading) return`

2024-01-29 04:49 UTC, git-marcopitra requested changes

2024-01-29 04:49 UTC, git-marcopitra commented on interface/sentio.ts
> +const COINS = {
move the `const`s to `constants` folder

2024-01-29 04:49 UTC, git-marcopitra commented on package.json
> +    "@interest-protocol/sui-amm-sdk": "interest-protocol/sui-amm-sdk",
here is supposed to have the version

2024-02-01 21:28 UTC, git-marcopitra requested changes

2024-02-01 21:28 UTC, git-marcopitra commented on interface/sentio.ts
> +export const COINS_MAP = {
remove all the `const`

2024-02-01 21:34 UTC, MarioBatalha approved these changes

2024-02-05 20:29 UTC, MarioBatalha approved these changes

2024-02-05 20:33 UTC, atilasousa approved these changes

2024-02-08 01:30 UTC, git-marcopitra approved these changes

2024-02-08 17:08 UTC, merged