:fire: delete elements folder
interest-protocol/sui-coins pull request #73
Opened 2024-01-18 20:26 UTC by git-marcopitra

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206189181392422

2024-01-22 21:46 UTC, MarioBatalha approved these changes

2024-01-23 01:22 UTC, KipandaJr requested changes

2024-01-23 01:22 UTC, KipandaJr commented on components/layout/footer/index.tsx
>          gap="0.25rem"
use the value on theme

2024-01-25 19:38 UTC, KipandaJr approved these changes

2024-01-25 20:06 UTC, atilasousa approved these changes

2024-01-25 20:06 UTC, merged